version: '3'

services:
###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!e6c59f011a8c518dc3bcc2d08b8ae6a6df2f893668428788c03c4461c70d3a33!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!e6c59f011a8c518dc3bcc2d08b8ae6a6df2f893668428788c03c4461c70d3a33!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - '8000:80'
###< symfony/mercure-bundle ###

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
#networks:
 # dev:
  #  driver: bridge